### ISSUE TITLE
Broken in Safari 14.1.2?

### ISSUE THREAD

**Issue by normen** [EddieCameron/keyword-searches-in-safari#12]
Hi,

since the recent update to Safari 14.1.2 SearchKey doesn't seem to work for me anymore. I don't see the icon in the Safari bar and the prefixes don't work. The extension lists in the Safari settings and its marked as enabled. I tried disabling, restarting Safari and re-enabling to no avail..

Thanks for this fantastic extension - its absolutely essential for me!

**Comment by normen** [comment]
Err.. Sorry but after disabling and re-enabling a few more times it seems the extension is working again... I'll keep an eye on this for a while, keeping this issue open for now as this was definitely real..

**Comment by EddieCameron** [comment]
I’ve seen this too, as well as with other extensions, throwing what look like permissions related errors. I might find something more concrete but at the moment i just think Safaris support for native extensions is not great. To be honest I’ve mostly given up on safari after too many issues like this.

**Comment by normen** [comment]
I see, thanks for the reply. I guess its a typical Apple thing, stray too far from what they intend you to do and it gets a bit rough - still because of many other things I really prefer Safari over other browsers so I hope this extension will be kept alive. Cheers!

**Comment by normen** [comment]
Closing this as I didn't see any issues on multiple machines and OS versions anymore, including the latest Safari 15.2 on Monterey (still on Intel Mac). Its one of the best Safari plugins! I only wish it came to iPadOS as well 😅
