### ISSUE TITLE
Cannot add custom urls

### ISSUE THREAD

**Issue by psaintemarie** [EddieCameron/keyword-searches-in-safari#4]
Hi,

When I try to add a custom URL, it's not saved.
This is on the App Store version 1.1 and macOS Big Sur Beta.

**Comment by psaintemarie** [comment]
URL looks like: https://github.com/search?q=repo%3AORGNAME%2FREPONAME+%s&type=Wikis&utf8=%E2%9C%93

**Comment by psaintemarie** [comment]
Ok I figured I needed to use {search} instead of %s.

**Comment by EddieCameron** [comment]
Oh no I was worried apple broke something again with big sur

**Comment by psaintemarie** [comment]
Yeah no that was just me not reading instructions, sorry for the noise and thanks for the tool, very nice and very useful !
