### ISSUE TITLE
Don't work this feature in Japanase

### ISSUE THREAD

**Issue by skikkh** [EddieCameron/keyword-searches-in-safari#8]
Mac OS: 11.0.1
Safari: 14.0.1 (16610.2.11.51.8)
keysearch: 1.1

As the title says, I can't use this feature in Japanese.
For example, when search "w 東京", the search result is "w 東京" by default search engine.

**Comment by EddieCameron** [comment]
Hi, try the version available here on Github (1.6) (I'll submit this to Apple now)

**Comment by EddieCameron** [comment]
Version on the app store has the fix now too
