### ISSUE TITLE
% is converted to %25 in URL causing search to fail

### ISSUE THREAD

**Issue by lydiaeaves** [EddieCameron/keyword-searches-in-safari#9]
Hi,

Added in the following search which works when tried directly through the browser:
https://cse.google.com/cse?cx=006680642033474972217%3A6zo0hx_wle8&q={search}

However, when I search using the extension the % sign gets encoded to %25 causing the search to fail.

URL is translated to:
https://cse.google.com/cse?cx=006680642033474972217%253A6zo0hx_wle8&q={search}

**Comment by EddieCameron** [comment]
Hi, thanks for this report, I was URL encoding the whole query instead of just the search term. A fix is in the latest release (1.7) https://github.com/EddieCameron/keyword-searches-in-safari/releases/tag/v1.7
